### ISSUE TITLE
Component does not perform section animation.

### ISSUE THREAD

**Issue by vishal-p** [badoo/ios-collection-batch-updates#2]
I've setup my sections and objects as following 
`
class CheckinItemsSection: NSObject, BMAUpdatableCollectionSection {

    public var uid: String = ""
    public var items: [Any] = []
    
    public override func isEqual(_ object: Any?) -> Bool {
    
        if  object is CheckinItemsSection {
            let c = object as! CheckinItemsSection
            return self.uid == c.uid
        }
        return false
    }
    
    
    override var hash: Int {
        return uid.hash
    }

    init(uid:String, items:[Any]){
        super.init()
        self.items = items
        self.uid = uid
    }
}

`
and actual object i'm rendering  is

```
@interface APGCheckin : MTLModel<MTLJSONSerializing,BMAUpdatableCollectionItem>

...
-(void)setRef:(NSString *)ref
{
    self.uid = ref;
    _ref = ref;
}

@end

```

I'm passing old and new model in BMACollectionUpdate.calculateUpdates method it performs row animations file but does not perform section animations.

**Comment by vmagaziy** [comment]
This is expected as because of internal limitations it's not possible to do both row and section animations simultaneously. The solution works w/ animations for situations where sections are not changed.

**Comment by RomanTruba** [comment]
@vmagaziy ok, I understand why it not working simultaneously for both rows and section. But why it ignores section animations when completely new section inserted or single section completely removed, without other sections been affected?

**Comment by Viacheslav-Radchenko** [comment]
@RomanTruba thank you for pointing out on this.
When we were implementing this algorithm we faced several issues when we had section's insertions/removals and items animations in the same batch update. 
In order not to overcomplicate algorithm by handling possible edge cases and also because in our case we didn't need support for this behaviour, we decided to go with simple reloadData in case if section change occurred.

As a workaround I would suggest to have a fixed number of sections which might be hidden if they are empty. Merging algorithm will work well in this case.

Otherwise you can patch it and implement proper handling for your particular case.

**Comment by Viacheslav-Radchenko** [comment]
I'll close this issue for now, because there is no plans to add this logic from our side in near future.
